### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Guibod** [jonDotsoy/gulp-docker-tasks#1]
Hi, I'm pretty new to Gulp tasks and I was wondering if you could provide some example on How-to-use-your-tasks.

Thanks

**Comment by JonDotsoy** [comment]
Thanks @Guibod.

It is relatively simple. only `.attach()` is used.

```
var gulp = require("gulp");
var Docker = require("gulp-docker-tasks");

var docker = new Docker();

docker.attach();
```

Also it was added to the current documentation.

**Comment by JonDotsoy** [comment]
91b9797b2dcaf3ddb41c16be6fc669da25fafb3b

**Comment by JonDotsoy** [comment]
#91b9797b2dcaf3ddb41c16be6fc669da25fafb3b

**Comment by Guibod** [comment]
Thanks :)
